### ISSUE TITLE
Meta API+OpenRouter API has language encoding issues.  #bugreport

### ISSUE THREAD

**Issue by sinanisler** [meta-llama/llama-stack#10]
I dont know if the problem exist only for OpenRouter end or Meta end.
Just incase I am reporting this problem to both parties.

https://sinanisler.com/wp-content/uploads/2024/07/2024-07-24-17-33-17.mp4

this problem doesn't happen on site only it happens on OpenRouter API too sadly we first discovered on API and started investigating and foundout problem happening on OpenRouter llama model.

Fix it please. 🙏
Thank you.

**Comment by dltn** [comment]
Hi, thanks for the report @sinanisler. This problem should be reported to OpenRouter.
