### ISSUE TITLE
`llama build stack` fails with image-type docker due to wrong build context

### ISSUE THREAD

**Issue by CarMiranda** [meta-llama/llama-stack#100]
I just installed the package with:
```bash
uv python pin 3.10.14
uv init
uv add llama-stack
```
This installed `llama-stack==0.0.36` and its dependencies in `.venv`.
Then, after activating the virtual environment, I tried to run `llama build stack` with name `my-local-stack`, image type `docker`, and the reference implementations for the remaining options.

The docker build command failed:
```
+ docker build -t llamastack-my-local-stack -f /tmp/tmp.1BizPTWiy8/Dockerfile /home/carlos/Documents/test-workspace/llaming-around/.venv/lib/python3.10/site-packages
...
Dockerfile:16
--------------------
  14 |     # ENTRYPOINT ["python", "-m", "llama_stack.distribution.server.server"]
  15 |
  16 | >>> ADD .venv/lib/python3.10/site-packages/llama_stack/configs/distributions/docker/my-local-stack-build.yaml ./llamastack-build.yaml
  17 |
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 5ba41c90-7513-48ee-a463-b1298c362883::zkxo9raxwxt0u06pbwzmhlxob: failed to walk /var/lib/docker/tmp/buildkit-mount3331234773/.venv/lib/python3.10/site-packages/llama_stack/configs/distributions/docker: lstat /var/lib/docker/tmp/buildkit-mount3331234773/.venv/lib/python3.10/site-packages/llama_stack/configs/distributions/docker: no such file or directory
```
Basically, the `*-build.yaml` file is not found because the docker builder context is the `site-package` folder within `.venv` but the first path in the ADD instruction is relative to the repo directory.

I modified this line:
https://github.com/meta-llama/llama-stack/blob/c8fa26482d5919365152e6bc2273c694847a5e5f/llama_stack/distribution/build_container.sh#L106

so now it reads:
```
add_to_docker "ADD llama_stack/configs/distributions/docker/$build_name-build.yaml ./llamastack-build.yaml"
```
It builds the image now!

Is this the correct way to fix the command? I can do a PR if necessary.

**Comment by matbee-eth** [comment]
I manually tagged it via: `docker image tag llamastack/llamastack-local-gpu llamastack-local-gpu`

**Comment by yanxi0830** [comment]
Thanks for raising the issue! This have been fixed in https://github.com/meta-llama/llama-stack/commit/ca7602a64289d272c20f4e702767caecb1fcafcf
