### ISSUE TITLE
Will it support RAG?

### ISSUE THREAD

**Issue by solitude-alive** [meta-llama/llama-stack#109]
Do you have plans to support Retrieval-Augmented-Generation (RAG), constructing a vector database based on personal data and then performing the corresponding retrieval and generation processes?

**Comment by marcelcastrobr** [comment]
> Do you have plans to support Retrieval-Augmented-Generation (RAG), constructing a vector database based on personal data and then performing the corresponding retrieval and generation processes?

+1

**Comment by yanxi0830** [comment]
Yes! We have support for RAG. You can find some examples in our llama-stack-apps repo: https://github.com/meta-llama/llama-stack-apps/tree/main/examples/agents.
