### ISSUE TITLE
Llama stack build fail

### ISSUE THREAD

**Issue by Pentar0o** [meta-llama/llama-stack#115]
Hey, 

I've launched the llama stack build with either python 3.10 and 3.12 and got this error all the time :
> Enter a name for your Llama Stack (e.g. my-local-stack): vision-11b
> Enter the image type you want your Llama Stack to be built as (docker or conda): conda

 Llama Stack is composed of several APIs working together. Let's configure the providers (implementations) you want to use for these APIs.
> Enter provider for the inference API: (default=meta-reference): meta-reference
> Enter provider for the safety API: (default=meta-reference): meta-reference
> Enter provider for the agents API: (default=meta-reference): meta-reference
> Enter provider for the memory API: (default=meta-reference): meta-reference
> Enter provider for the telemetry API: (default=meta-reference): meta-reference
 
 > (Optional) Enter a short description for your Llama Stack: cortana
Traceback (most recent call last):
  File "/home/penta/.local/bin/llama", line 8, in <module>
    sys.exit(main())
  File "/home/penta/.local/lib/python3.10/site-packages/llama_stack/cli/llama.py", line 44, in main
    parser.run(args)
  File "/home/penta/.local/lib/python3.10/site-packages/llama_stack/cli/llama.py", line 38, in run
    args.func(args)
  File "/home/penta/.local/lib/python3.10/site-packages/llama_stack/cli/stack/build.py", line 265, in _run_stack_build_command
    self._run_stack_build_command_from_build_config(build_config)
  File "/home/penta/.local/lib/python3.10/site-packages/llama_stack/cli/stack/build.py", line 104, in _run_stack_build_command_from_build_config
    Path(os.getenv("CONDA_PREFIX")).parent
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Any idea ?

**Comment by alecswan** [comment]
This doesn't appear to be conda-specific since I am getting the same error with "docker" type image after installing from source.

> > Enter the image type you want your Llama Stack to be built as (docker or conda): docker
> 
>  Llama Stack is composed of several APIs working together. Let's configure the providers (implementations) you want to use for these APIs.
> > Enter provider for the inference API: (default=meta-reference): meta-reference
> > Enter provider for the safety API: (default=meta-reference): meta-reference
> > Enter provider for the agents API: (default=meta-reference): meta-reference
> > Enter provider for the memory API: (default=meta-reference): meta-reference
> > Enter provider for the telemetry API: (default=meta-reference): meta-reference
>  
>  > (Optional) Enter a short description for your Llama Stack:
> Traceback (most recent call last):
>   File "/tools/python/v-envs/llama-stack-python3.10/bin/llama", line 8, in <module>
>     sys.exit(main())
>   File "/dev/llama-stack/llama_stack/cli/llama.py", line 44, in main
>     parser.run(args)
>   File "/dev/llama-stack/llama_stack/cli/llama.py", line 38, in run
>     args.func(args)
>   File "/dev/llama-stack/llama_stack/cli/stack/build.py", line 265, in _run_stack_build_command
>     self._run_stack_build_command_from_build_config(build_config)
>   File "/dev/llama-stack/llama_stack/cli/stack/build.py", line 115, in _run_stack_build_command_from_build_config
>     return_code = build_image(build_config, build_file_path)
>   File "/dev/llama-stack/llama_stack/distribution/build.py", line 78, in build_image
>     script = pkg_resources.resource_filename(
>   File "/tools/python/v-envs/llama-stack-python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1384, in resource_filename
>     return get_provider(package_or_requirement).get_resource_filename(
>   File "/tools/python/v-envs/llama-stack-python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 424, in get_provider
>     return _find_adapter(_provider_factories, loader)(module)
>   File "/tools/python/v-envs/llama-stack-python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1667, in __init__
>     self.module_path = os.path.dirname(getattr(module, '__file__', ''))
>   File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 152, in dirname
>     p = os.fspath(p)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by bhargavyagnik** [comment]
@Pentar0o how are you running the command `llama stack build`? I think that needs to be executed inside a conda environment. That might be the cause.

**Comment by alecswan** [comment]
@bhargavyagnik , [getting started](https://github.com/meta-llama/llama-stack/blob/main/docs/getting_started.md) instructions seam to suggest that `pip install llama-stack` is sufficient and Conda is not required. I would strongly caution against making Conda a hard dependency for llama-stack's functionality.

**Comment by Pentar0o** [comment]
@alecswan agree, conda shouldn't be mandatory as it's not for equivalent solution like exo or ollama.

**Comment by Pentar0o** [comment]
> Thanks for raising the issue. Could you check if you have your CONDA_PREFIX set via
> 
> ```
> echo $CONDA_PREFIX
> ```

I'm not using conda because I didn't understood it was mandatory and I prefer not using it for performance / maintenance issues. Is there any way not using conda for llama-stack ?

**Comment by russellb** [comment]
You can use `docker` as the image type for your build instead of conda. Can you try that?

**Comment by Pentar0o** [comment]
I succeeded to do it with conda but I had other problems after so I'll wait couple of releases to give it a try again, thank you for your support.

**Comment by raghotham** [comment]
Please create a new issue with the other problems you are facing if you can.
