### ISSUE TITLE
llama-stack.png seems to be missing in the resource folder

### ISSUE THREAD

**Issue by rvs** [meta-llama/llama-stack#116]
Documentation in the resource folder refers to https://github.com/meta-llama/llama-stack/blob/main/docs/resources/llama-stack.png but the file seems to be missing

**Comment by yanxi0830** [comment]
thx for raising the issue! fixed in https://github.com/meta-llama/llama-stack/commit/2802ac8e9dff82aa35e65c89fbbb4973cddceb53
