### ISSUE TITLE
parameter to choose llama cache path

### ISSUE THREAD

**Issue by MaximeRivest** [meta-llama/llama-stack#129]
https://github.com/meta-llama/llama-stack/blob/eb526b4d9b7b8df1852759ebb8531fbdab22ed26/llama_stack/distribution/utils/config_dirs.py#L11

On EC2 instance I tend to want to put it in volumes, home is only 45gb

**Comment by yanxi0830** [comment]
Thanks for the feedback! We have added https://github.com/meta-llama/llama-stack/pull/137 to allow you to use ENV for specifying Llama cache path. 

```
export LLAMA_STACK_CONFIG_DIR=/custom/path/to/.llama

llama download --source meta --model-id Llama3.2-1B
```
