### ISSUE TITLE
Failing to build llama-stack on Mac OS X

### ISSUE THREAD

**Issue by genbit** [meta-llama/llama-stack#135]
Followed Getting Started guide, tried to build locally on Mac OS 15.0 (M1):

```Collecting fairscale
  Using cached fairscale-0.4.13.tar.gz (266 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement fbgemm-gpu==0.8.0 (from versions: none)
ERROR: No matching distribution found for fbgemm-gpu==0.8.0
Failed to build target my-local-stack with return code 1
```

**Comment by goooverhub** [comment]
+1. not sure if fbgemm-gpu is on macos

**Comment by californias66** [comment]
I'm getting the same issue, no way macOS can't build this? What am I doing wrong?

**Comment by bhargavyagnik** [comment]
The current inference supports only Cuda-based drivers, if you want to build on macos, you can use support with external inference like Ollama. It would work with that.

**Comment by genbit** [comment]
Thanks @bhargavyagnik for pointers. 

This is how it worked for me:
```bash
# shows me list of templates available for build command
$ llama stack build --list-templates

# use local-ollama inferencing
$ llama stack build --template local-ollama --name my-local-stack
```

This builds a stack using `meta-reference` for everything except using `remote::ollama` for inferencing.

**Comment by californias66** [comment]
Thank you fam you're all GOATS fsho 🙏🏽🔥😮‍💨
