### ISSUE TITLE
image_type in a template is not honored

### ISSUE THREAD

**Issue by russellb** [meta-llama/llama-stack#146]
I created a new template that had `image_type: docker`. I think tried to build it like this:

```
llama stack build --template my-new-template --name my-name
```

However, the build used `conda` instead of `docker` (which is why I hit #145).

The reason is that no matter what is in the template, the value from the `--image-type` CLI argument is used instead. The override happens at this line:

https://github.com/meta-llama/llama-stack/blob/b646167d94857a7023add6a3c45239edc583ef0a/llama_stack/cli/stack/build.py#L186

One possible fix would be to always use the value from the template, unless the `--image-type` argument is specified explicitly.

**Comment by yanxi0830** [comment]
Thanks for your valuable feedback! Fixed in https://github.com/meta-llama/llama-stack/pull/147
