### ISSUE TITLE
Ollama build docker image still looks for GPU support on run

### ISSUE THREAD

**Issue by clearstorm-tech** [meta-llama/llama-stack#150]
If I run build for ollama with docker, after configuring and running the docker image, the docker image still looks for GPU support and fails.

Steps to recreate.

    llama stack build --template local-ollama --name llama-stack-test-docker --image-type docker

 Dockerfile created successfully in /var/folders/7f/xb01fy750wgczjwyw164pch00000gq/T/tmp.A8IWK2zsAd/DockerfileFROM python:3.10-slim

     llama stack configure llamastack-llama-stack-test-docker

After configuring with port 4001
YAML configuration has been written to `/app/builds/llama-stack-test-docker-run.yaml.
llama stack run llama-stack-test-docker --port PORT

    llama stack run llama-stack-test-docker --port 4001

  docker run -it -p 4001:4001 -v ~/.llama/builds/docker/llama-stack-test-docker-run.yaml:/app/config.yaml -v ~/.llama:/root/.llama --gpus=all llamastack-llama-stack-test-docker python -m llama_stack.distribution.server.server --yaml_config /app/config.yaml --port 4001
  docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
  nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

This is using --gpus=all. 

If I remove --gpus=all and start manually it starts. 

        docker run -it -p 4001:4001 -v ~/.llama/builds/docker/llama-stack-test-docker-run.yaml:/app/config.yaml -v ~/.llama:/root/.llama llamastack-llama-stack-test-docker python -m llama_stack.distribution.server.server --yaml_config /app/config.yaml --port 4001

**Comment by yanxi0830** [comment]
Yes, you may run with 
```
docker run -it -p 4001:4001 -v ~/.llama/builds/docker/llama-stack-test-docker-run.yaml:/app/config.yaml llamastack-llama-stack-test-docker python -m llama_stack.distribution.server.server --yaml_config /app/config.yaml --port 4001
```

For `llama stack run`, could you help check that if you have set your `LLAMA_CHECKPOINT_DIR`? Having this environment var set will trigger docker run with `--gpus=all` flag.

**Comment by clearstorm-tech** [comment]
@yanxi0830 Thank you for your response. 

You are right I had LLAMA_CHECKPOINT_DIR still set from a previous attempt. 

Removing this runs from my shell runs the command without gpu support.
