### ISSUE TITLE
small bug in text_completion function

### ISSUE THREAD

**Issue by avanindra** [meta-llama/llama-stack#16]
Hi, prompt_tokens = self.tokenizer.encode(x, bos=True, eos=False) should take prompt as input , not x, in llama_toolchain/inference/generation.py. Encountered it while using directly the Llama class instead of recommended client server route.

    def text_completion(
        self,
        prompt: str,
        temperature: float = 0.6,
        top_p: float = 0.9,
        max_gen_len: Optional[int] = None,
        logprobs: bool = False,
        echo: bool = False,
    ) -> Generator:
        if (
            max_gen_len is None
            or max_gen_len == 0
            or max_gen_len >= self.model.params.max_seq_len
        ):
            max_gen_len = self.model.params.max_seq_len - 1

        **prompt_tokens = self.tokenizer.encode(x, bos=True, eos=False)**

        yield from self.generate(
            model_input=ModelInput(tokens=prompt_tokens),
            max_gen_len=max_gen_len,
            temperature=temperature,
            top_p=top_p,
            logprobs=logprobs,
            echo=echo,
        )

**Comment by ashwinb** [comment]
Fixed https://github.com/meta-llama/llama-stack/commit/069d877210582bfe1aac1e5b1bbe62670d22507c
