### ISSUE TITLE
[functionality] Implement completion() methods 

### ISSUE THREAD

**Issue by ashwinb** [meta-llama/llama-stack#168]
Most of the current inference providers only implement the `chat_completion()` method. The `completion()` method raises a `NotImplementedError`. We should implement this method for all the inference providers:

- meta-reference
- fireworks
- together
- ollama
- bedrock

**Comment by niltonheck** [comment]
Would love to help. Will check the missing implementations.

**Comment by C0deXG** [comment]
Am currently working on the issue will update in hour

**Comment by C0deXG** [comment]
> Would love to help. Will check the missing implementations.

am working on the issue too, should i stop?

**Comment by niltonheck** [comment]
Oh no, please continue! Are you going to implement all missing implementations? Maybe I can help with some of those.

**Comment by C0deXG** [comment]
> Oh no, please continue! Are you going to implement all missing implementations? Maybe I can help with some of those.

i am will try to do some but i may need help with the other thanks!

**Comment by niltonheck** [comment]
@ashwinb are the `kvstore_impl` and `EmbeddingIndex` implementations being handled by the team internally?
