### ISSUE TITLE
docker: workflow now requires running configure twice

### ISSUE THREAD

**Issue by russellb** [meta-llama/llama-stack#169]
#159 added a call to `llama stack configure` to `build_container.sh`. The output is put into a temporary location so that it can be injected into the container. However, `llama stack run` expects this file in a different location, `~/.llama/builds/docker/...`. For `run` to work, `llama stack configure` must be run again after the build. Running it twice doesn't seem ideal.

One possible change is to update `start_container.sh` to understand that the config file is inside the container instead of mounting it. The downside is that additional `llama stack configure` runs after the build would no longer take effect.

Another option would be to change `build_container.sh` to ensure the config file ends up in the expected location so that `run` works without having to run `configure` a second time.''

cc @yanxi0830

**Comment by yanxi0830** [comment]
Yes. This was done on purpose to bake the run.yaml file inside the docker image when building s.t.

1. Consumers of docker image do not have to run `llama stack configure`, and can directly run
```
docker image pull llamastack/llamastack-local-gpu
docker run -it -p 5000:5000 -v ~/.llama:/root/.llama --gpus=all llamastack-local-gpu
```

2. `llama stack configure` is not required (but feasible), to interact with docker container. 

We will update the new developer flow for docker and recommend (1).

**Comment by russellb** [comment]
I understand that 1 is a simple flow as an end user, but in my case I'm working on llama-stack itself. I know I can do 2. It's just weird since if I do a build, I went through configure, and then I have to do it immediately again for `run` to work correctly.

In my case, running docker run (or podman run) isn't great either, because there's some extra logic under `llama stack run` that's convenient:

- disabling SELinux
- mounting the source dir into the container 
- mounting the checkpoint dir

I guess I'm also a bit confused about what the vision is for the UX with the `llama` tool, like who is it built for? what workflows is intended for vs. not?

**Comment by ashwinb** [comment]
Yes, I think we need to fix this and make it work for the persona which is using both `llama` CLI and the persona which is not.

@russellb to make it clear in terms of expected usage:
- we are seeing that there's the "client" user who installs `llama-stack-apps` and thinks about the stack as a customer. they run one command (with some lightweight config edits) and stack server is up. now they are off into app land. this customer has limited use of the `llama stack` set of CLI commands.
- the other user is someone like you -- who is working on the stack components. for this persona, we need to continue to have `llama stack` subcommands work as expected.

**Comment by russellb** [comment]
Thanks, @ashwinb - sounds good

**Comment by ashwinb** [comment]
@yanxi0830 Can we make it so someone who is using `llama stack` CLI commands does not need to run configure twice?

**Comment by yanxi0830** [comment]
> Another option would be to change build_container.sh to ensure the config file ends up in the expected location so that run works without having to run configure a second time.''

I think this may be better as we still want to support `configure` for docker images. Another option is to add a `--configure` flag to `llama stack build` to decide whether we want to run configure to bake the run.yaml file.

**Comment by yanxi0830** [comment]
New flow in here for docker, supports `build -> run` directly without need to run `configure` again:  https://github.com/meta-llama/llama-stack/pull/171

**Comment by yanxi0830** [comment]
Fixed in https://github.com/meta-llama/llama-stack/pull/171
