### ISSUE TITLE
llama download obscure signed url requirement

### ISSUE THREAD

**Issue by ShadiCopty** [meta-llama/llama-stack#202]
I am trying to use llama-stack on a linux (on AWS x86_64). After installing anaconda & llama-stack
llama-build was successful
llama configure was successful.

I was told to "llama download --model-id Llama3.1-8B-Instruct"

I'm receiving the following request, not sure where to get this from, any ideas?

Please provide the signed URL you received via email (e.g., https://llama3-1.llamameta.net/
*?Policy...):

**Comment by Itime-ren** [comment]
https://www.llama.com/llama-downloads/

**Comment by ShadiCopty** [comment]
Thank you Itime-ren! 
Would be nice to have this instead of (e.g, https://....).

Also, curious why I didn't need to go through this process with ollama (download was much more streamlined and didn't require a stop at llama.com

**Comment by ShadiCopty** [comment]
Leaving open for the suggestions above

**Comment by Itime-ren** [comment]
ollama 提供的是 gguf模型 是在meta的模型上转换过的，提供下载的是ollama自己的网站，meta和huggingface的需要这个授权链接，你可能需要从https://hf-mirror.com/ 尝试下载，如果直接访问huggingface有障碍，但是同样需要授权

**Comment by russellb** [comment]
I posted a PR to improve the help text with the URL needed to request access -- #204
