### ISSUE TITLE
How to run 90B ?

### ISSUE THREAD

**Issue by nikolaydubina** [meta-llama/llama-stack#205]
I could not find instructions. ollama does not support it[^1], llama.cpp does not support it[^2], Google Vertex AI (only preview)[^3]

on my local machine with 128 GB RAM (and 2TB SSD) it is crashing with OOM

is there distributed mode? quantization? any guideline how to run it? how does Meta itself run it?

[^1]: https://ollama.com/blog/llama3.2
[^2]: https://github.com/ggerganov/llama.cpp/issues/9643
[^3]: https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/llama#llama-3.2-90b-preview

**Comment by raghotham** [comment]
Here are some examples of where 90B should work:

https://aws.amazon.com/bedrock/llama/
https://www.together.ai/blog/llama-3-2-vision-stack
https://fireworks.ai/blog/llama32-with-fireworks

**Comment by nikolaydubina** [comment]
none of these examples are self hosted.

how to run 90B self hosted version using llama-stack?
