### ISSUE TITLE
Add custom volume mounts to docker runtime

### ISSUE THREAD

**Issue by romilbhardwaj** [meta-llama/llama-stack#211]
I'm trying to implement an inference provider for [SkyPilot](https://github.com/skypilot-org/skypilot), which needs the user's local cloud credentials to be available inside the llama-stack container.

The [recommended way](https://skypilot.readthedocs.io/en/latest/getting-started/installation.html#quick-alternative-trying-in-docker) to do so is to add local credential dirs as volume mounts for the docker container. What's the best way to attach volume mounts to the llama stack container?

I assume they could be handled similar to how `LLAMA_STACK_DIR` and `LLAMA_CHECKPOINT_DIR` are read from envvars in [start_container.sh](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/distribution/start_container.sh), but wondering if there are plans to better support this in inference provider API?

**Comment by yanxi0830** [comment]
Yes, this can be done similar to `LLAMA_CHECKPOINT_DIR` and bind volume mounts to docker containers via `-v <host_path>:<container_path>`.
