### ISSUE TITLE
Unable to run `llama` on windows: "'llama' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by thecoderok** [meta-llama/llama-stack#223]
Hey I'm trying to try to download and run llama, but I'm stuck at the second step.

First step: done

```
>pip install llama-stack
```

Second step: failing

```
>llama model list
'llama' is not recognized as an internal or external command,
operable program or batch file.
```
I'm running Windows 11: 
```
>ver

Microsoft Windows [Version 10.0.22631.4249]
```

pip:

```
>pip --version
pip 24.2 from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip (python 3.12)

```

Can anyone please help?

**Comment by mgl12432** [comment]
I'm also faced the same problem, I tried with powershell. looks like the path is not set to the shell via environment variables. I tried that too but didnt work. So i followed a different approach. 

Create a python env with following command : python -m venv <env name>
activate the environment : <env name>\Scripts\activate

if the second command didn't work try following with shell on admin mode : Set-ExecutionPolicy RemoteSigned
 
Now : pip install llama-stack

Then you can go on....

**Comment by thecoderok** [comment]
thank you @mgl12432 !
I was also able to resolve this issue by installing Conda: https://anaconda.org/anaconda/conda

**Comment by dpmmx** [comment]
During installation, you might encounter a warning like this:

WARNING: The scripts install-wheel-from-presigned.exe and llama.exe are installed in 'C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

This means that the llama command is not available in your environment, and you’ll need to manually add it to your system's PATH. Alternatively, you can specify the full path when using llama, like so:

cmd>C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\llama model list

**Comment by iibw** [comment]
I got this error when installing llama-stack in a Python 3.8 Anaconda environment. Creating a Python 3.10 Anaconda environment and installing it there worked with no issues. I guess llama-stack does not support Python 3.8.

**Comment by Randy-Hodges** [comment]
I've tried all of the above and nothing is working. I just don't have a llama.py file on my computer

**Comment by aileentang** [comment]
@iibw  is correct, this is what came up when I tried to install it with the git clone

```
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10; 0.0.10 Requires-Python >=3.10; 0.0.11 Requires-Python >=3.10; 0.0.12 Requires-Python >=3.10; 0.0.13 Requires-Python >=3.10; 0.0.14 Requires-Python >=3.10; 0.0.15 Requires-Python >=3.10; 0.0.16 Requires-Python >=3.10; 0.0.17 Requires-Python >=3.10; 0.0.18 Requires-Python >=3.10; 0.0.19 Requires-Python >=3.10; 0.0.2 Requires-Python >=3.10; 0.0.21 Requires-Python >=3.10; 0.0.23 Requires-Python >=3.10; 0.0.24 Requires-Python >=3.10; 0.0.3 Requires-Python >=3.10; 0.0.35 Requires-Python >=3.10; 0.0.36 Requires-Python >=3.10; 0.0.37 Requires-Python >=3.10; 0.0.38 Requires-Python >=3.10; 0.0.39 Requires-Python >=3.10; 0.0.4 Requires-Python >=3.10; 0.0.40 Requires-Python >=3.10; 0.0.41 Requires-Python >=3.10; 0.0.42 Requires-Python >=3.10; 0.0.43 Requires-Python >=3.10; 0.0.44 Requires-Python >=3.10; 0.0.45 Requires-Python >=3.10; 0.0.46 Requires-Python >=3.10; 0.0.47 Requires-Python >=3.10; 0.0.48 Requires-Python >=3.10; 0.0.49 Requires-Python >=3.10; 0.0.5 Requires-Python >=3.10; 0.0.50 Requires-Python >=3.10; 0.0.53 Requires-Python >=3.10; 0.0.54 Requires-Python >=3.10; 0.0.55 Requires-Python >=3.10; 0.0.56 Requires-Python >=3.10; 0.0.57 Requires-Python >=3.10; 0.0.58 Requires-Python >=3.10; 0.0.59 Requires-Python >=3.10; 0.0.6 Requires-Python >=3.10; 0.0.60 Requires-Python >=3.10; 0.0.61 Requires-Python >=3.10; 0.0.62 Requires-Python >=3.10; 0.0.63 Requires-Python >=3.10; 0.0.7 Requires-Python >=3.10; 0.0.8 Requires-Python >=3.10; 0.0.9 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement llama-models>=0.0.63 (from llama-stack) (from versions: none)
ERROR: No matching distribution found for llama-models>=0.0.63
```

**Comment by lcundiff** [comment]
If you don't want to use a virtual environment and llama-stack is installing anything into your Python Scripts folder (which it didn't work me for some reason - just into site-packages), just download the GPT4 GUI and download the Llama model from there - no terminal required: https://www.nomic.ai/gpt4all

**Comment by liliaurmazova** [comment]
> During installation, you might encounter a warning like this:
> 
> WARNING: The scripts install-wheel-from-presigned.exe and llama.exe are installed in 'C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH. Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> 
> This means that the llama command is not available in your environment, and you’ll need to manually add it to your system's PATH. Alternatively, you can specify the full path when using llama, like so:
> 
> cmd>C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\llama model list

Thanks, this way worked for me!

**Comment by XuZhangNYU** [comment]
> I got this error when installing llama-stack in a Python 3.8 Anaconda environment. Creating a Python 3.10 Anaconda environment and installing it there worked with no issues. I guess llama-stack does not support Python 3.8.

Same. I used Python 3.8. I changed to 3.10 and then reinstall llama-stack, everything now works
