### ISSUE TITLE
Switching between stacks

### ISSUE THREAD

**Issue by anandhuh1234** [meta-llama/llama-stack#226]
I have created and configured two stacks

```bash
 llama stack build --template local --name dev1
 llama stack configure dev1

 llama stack build --template local --name dev2
 llama stack configure dev2
```
And it is running in the port 8090. 
```bash
llama stack run dev1 --port 8090 --disable-ipv6 
```
How to swtich to dev2 to run on the same port? I am trying to automate switching between stacks in linux.

**Comment by damon1205** [comment]
To switch between dev1 and dev2 stacks running on the same port (8090) using a script or automation in Linux, you can automate stopping the current stack and starting the new stack on the same port. Here’s how you can structure it:

1. Stop the Currently Running Stack:

- Before switching to a new stack (dev2), stop the current stack (dev1).

- Use llama stack stop command or kill the process running on port 8090.

2. Start the New Stack:

- Once the dev1 stack is stopped, you can start dev2 on port 8090.

3. Automate the Process with a Shell Script: You can create a simple shell script to automate switching between the two stacks.
