### ISSUE TITLE
Add `llama download` support for multiple models with comma-separated list

### ISSUE THREAD

**Issue by dltn** [meta-llama/llama-stack#233]
The Llama CLI streamlines downloading a Llama model:

```
llama download  --model-id Llama3.1-70B-Instruct
```

A nice improvement would be enabling `--model-ids MODEL_A,MODEL_B` to download multiple models in one go!

**Comment by tamdogood** [comment]
PR: https://github.com/meta-llama/llama-stack/pull/261
