### ISSUE TITLE
I cant use llama-stack on ubuntu 20.04 even ı downloaded with pip 

### ISSUE THREAD

**Issue by korkmazemin1** [meta-llama/llama-stack#250]
even ı pipped the llama stack on ubuntu 20.04 I m facing with this issue  

and ı tried tried sudo snap install its an offtopic command line code for me 

`comp@comp:~$ llama model-list`

`Command 'llama' not found, but can be installed with:`

`sudo snap install llama`

**Comment by yanxi0830** [comment]
You can check the installation guide here: https://github.com/meta-llama/llama-stack/tree/main?tab=readme-ov-file#installation

From [pypi](https://pypi.org/project/llama-stack/)
```
pip install llama-stack
```

From Source: 
```
mkdir -p ~/local
cd ~/local
git clone git@github.com:meta-llama/llama-stack.git

conda create -n stack python=3.10
conda activate stack

cd llama-stack
$CONDA_PREFIX/bin/pip install -e .
```

**Comment by korkmazemin1** [comment]
ı fixed with python version to thanks for help @yanxi0830  and @xyzws
