### ISSUE TITLE
untagged Docker images

### ISSUE THREAD

**Issue by nikolaydubina** [meta-llama/llama-stack#256]
it is best practice to tag docker images with information about version of source code

both gpu and cpu images don't have tags and have implicit `latest` only.

(e.g. for myself I had to add my own tags when pushing images to private repository. ideally I would use just same tags as ground truth, but there is none for now.)

https://hub.docker.com/repository/docker/llamastack/llamastack-local-gpu/general
https://hub.docker.com/repository/docker/llamastack/llamastack-local-cpu/general

<img width="726" alt="image" src="https://github.com/user-attachments/assets/69a98d24-1dab-4017-bc9e-6efadeab42d5">

**Comment by yanxi0830** [comment]
Thanks for the suggestion! We will begin to tag our docker images for every PyPI package release in the future. As our updates are happening daily, we can only guarantee support for latest docker image.
