### ISSUE TITLE
llama-stack-client: command not found

### ISSUE THREAD

**Issue by alexhegit** [meta-llama/llama-stack#361]
### System Info

N/A

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

llama-stack-client: command not found which mentioned in https://github.com/meta-llama/llama-stack/blob/main/distributions/ollama/README.md 

### Error logs

Follow the https://github.com/meta-llama/llama-stack/blob/main/distributions/ollama/README.md and got this issue

![image](https://github.com/user-attachments/assets/74440f1b-2edb-4021-a1b6-7176840fb8b9)

### Expected behavior

llama-stack-client could run

**Comment by stevegrubb** [comment]
I had a similar problem and then pip installed llama-stack-client.

**Comment by yanxi0830** [comment]
Closing. We have added `llama-stack-client` package as dependency in https://github.com/meta-llama/llama-stack/blob/de7af28756e6558fae2679b8034d4664cd1ce776/requirements.txt#L6
