### ISSUE TITLE
Support guided decoding with vllm and remote::vllm

### ISSUE THREAD

**Issue by ashwinb** [meta-llama/llama-stack#391]
### 🚀 The feature, motivation and pitch

(fireworks, together, meta-reference) support guided decoding (specifying a json-schema for example, as a "grammar" for decoding) with inference. vLLM supports this functionality -- enable that in the API

### Alternatives

No alternatives, this is a core feature that must be supported by all providers (as far as possible).

**Comment by aidando73** [comment]
Hi @ashwinb, @yanxi0830 -  I came across this issue and I'm really interested in contributing to it. Do you mind if I take a stab at this issue?

I've reviewed the contributing guidelines and the existing codebase, and I believe I have a good understanding of what needs to be done. However, if there are any specific details or guidelines you think I should be aware of, please let me know.

**Comment by ashwinb** [comment]
@aidando73 Please go ahead. I remember seeing a PR about this (but it was not quite on the correct track) so I think you are good to do. Re: guidelines, consider the `response_format` parameter here: https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/remote/inference/vllm/vllm.py#L86 .. you'd need to understand what this parameter does semantically. Then you'd need to know whether vllm's API allows for this (I think it does hence the issue) and then make sure you appropriately translate. 

Finally, when everything is ready, you'd need to run the tests inside `providers/tests/inference/test_text_inference.py` (test_structured_output) to check if all is well. Please ask us any questions.

**Comment by aidando73** [comment]
Thanks @ashwinb 🙏, will get started

**Comment by terrytangyuan** [comment]
@aidando73 Thanks! Please feel free to tag me for review once it's ready.

**Comment by aidando73** [comment]
Ok @ashwinb @terrytangyuan PR is ready for review: https://github.com/meta-llama/llama-stack/pull/528 👈 . Lmk if I've missed anything.

**Comment by terrytangyuan** [comment]
We can close this?

**Comment by ashwinb** [comment]
Yes I think so
