### ISSUE TITLE
I Don’t Understand FunctionCallToolDefinition - Request for Help

### ISSUE THREAD

**Issue by JoseGuilherme1904** [meta-llama/llama-stack#396]
### 🚀 The feature, motivation and pitch

Please, I need a tool defined as FunctionCallToolDefinition to be executed by llama stack run.

I tried this definition and encountered the following error. I believe remote_execution parameter  doesn’t work as expected.

`{
"input_shields": [
"string"
],
"output_shields": [
"string"
],
"type": "function_call",
"function_name": "string",
"description": "string",
"parameters": {
"property1": {
"param_type": "string",
"description": "string",
"required": true,
"default": { }
},
"property2": {
"param_type": "string",
"description": "string",
"required": true,
"default": { }
}
},
"remote_execution": {
"url": "http://example.com/",
"method": "GET",
"params": {
"property1": { },
"property2": { }
},
"headers": {
"property1": { },
"property2": { }
},
"body": {
"property1": { },
"property2": { }
}
}
}`

`                AgentConfigToolFunctionCallToolDefinition(
                    type = "function_call",
                    function_name = "PesquisaWebCPF",
                    description = "Tendo um ou mais CPFs, utilize essa função para pesquisar todos os dados de um ou mais funcionários por CPF. Os dados retornados incluem dados cadastrais, financeiros, de férias, afastamentos, dependentes, endereço, telefones, e emails.",
                    input_shields = ["string", "string", "string"],
                    output_shields =  ["string", "string", "string"],
                    parameters = {
                        "cpfs": {
                            "param_type": "array",
                            "description": "Uma lista de números de CPF para pesquisa (formato: XXXXXXXXXXX).",
                            "required": True
                        }
                    },
                    remote_execution = {
                        "url": "http://localhost/a.php",
                        "method": "GET",
                        "params": {
                            "cpfs": "{cpfs}"
                        }
                    }
                ),`

 However, I don’t actually need remote_execution; instead, I’d like to embed a function directly into the agent by developing it as a tool in builtin.py. For example:`class FunctionCall(SingleMessageBuiltinTool):`

when calling remote_execution I get the following error:

Traceback (most recent call last):
File "/home/guilherme/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
await app(scope, receive, sender)
File "/home/guilherme/.local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
response = await f(request)
File "/home/guilherme/.local/lib/python3.10/site-packages/fastapi/routing.py", line 346, in app
raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'model_attributes_type', 'loc': ('body', 'agent_config', 'tools', 0, 'function_call', 'remote_execution', 'url'), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 'http://localhost/a.php'}]
INFO: 127.0.0.1:46906 - "POST /agents/create HTTP/1.1" 400 Bad Request

Thanks,
Guilherme

**Comment by yanxi0830** [comment]
The error suggests that incorrect request params to /agents/create. `remote_execution` is a placeholder and not being consumed currently. 

You can find a sample example using function_call in https://github.com/meta-llama/llama-stack-apps/blob/22deb4a795632b630ef3ac9c5072b6bb98af9d67/examples/agents/e2e_loop_with_custom_tools.py#L44-L65

**Comment by JoseGuilherme1904** [comment]
This is one of the examples that doesn't work. I have already mentioned this in other topics. Moreover, the example is confusing because it doesn't show the execution being done with llama stack run but rather separately on the client side. In the example, I don’t see the integration between a custom function and other memory functions being part of the neural network’s execution plan.

It would be helpful for people like me if the development team’s responses were more detailed, spending more time understanding the issue. For instance, there is a manual, and you mention that the remote_execution parameter in FunctionCallToolDefinition cannot be consumed. So, how can one know what works and what doesn’t within the current documentation?

Your example e2e_loop_with_custom_tools.py doesn’t run using ollama; it gives the following error: ValueError: Shield llama_guard not served by provider: meta-reference. Make sure there is a Safety provider serving this shield.

It is not possible to run without ollama because, through meta-reference, I couldn’t find a way to manage more than one network card to distribute max_seq_len in memory across two or more cards, and provider_type meta-reference also leads to VRAM overflow.

I have been studying your library daily because I believe in the project, but the brief responses pointing to issues that do not work or lack relevance to the integrated execution of the tools provided on the Llama Stack server make it very challenging.

I am going to develop my own plugin on the server, similar to those that exist today for PhotogenTool, BingSearch, and BraveSearch. It would be more helpful if you could guide me on the path I should take to add this new plugin and inform me if your team plans to improve the integration of a custom function directly on the Llama Stack server so that this custom function becomes part of the execution plan for turn steps.

Could you please help me, sir?
Thank you very much.

**Comment by yanxi0830** [comment]
@JoseGuilherme1904 Thanks for the detailed feedback, and I'm sorry you found the existing pointers is not helpful. 

> Moreover, the example is confusing because it doesn't show the execution being done with llama stack run but rather separately on the client side.

You are right. The example with custom tool using the `function_call` tool in AgentConfig's tools as ToolDefinition ([code pointer](https://github.com/meta-llama/llama-stack/blob/6192bf43a4ce6ae3ac03f7fd0eea22c261f10e4d/llama_stack/providers/inline/agents/meta_reference/agent_instance.py#L757-L772)). 

For Builtin tools, these will be executed on the Llama Stack server. For custom tools, these are defined by client and executed by client after getting Agent's response, and parsing the output ([code](https://github.com/meta-llama/llama-stack-client-python/blob/0901251a3370ea639ad7a2bb6c76ab99692219a0/src/llama_stack_client/lib/agents/agent.py#L47)). 

By implementing `FunctionCall(SingleMessageBuiltinTool)`, this will be a CustomTool that is executed on the client, using `function_call` tool definition. 

For current supported Builtin tools (e.g. PhotogenTool, BingSearch, BraveSearch) that are executed on the llama stack server, you may find example implemenetations in this code pointer: https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/inline/agents/meta_reference/tools/builtin.py#L2

> example e2e_loop_with_custom_tools.py doesn’t run using ollama; it gives the following. error: ValueError: Shield llama_guard not served by provider: meta-reference. Make sure there is a Safety provider serving this shield.

This is a separate common error that we are addressing. You can temporarily bypass running safety shields with the script by using the `--disable-safety` flag. 

> I have been studying your library daily because I believe in the project, but the brief responses pointing to examples that do not work or lack relevance to the integrated execution of the tools provided on the Llama Stack server make it very challenging.

Thanks for your feedback! We are actively working on improving the documentation and overall usage of our APIs. For example, we have WIP of using custom tools [here](https://github.com/meta-llama/llama-stack/blob/docs_improvement/docs/zero_to_hero_guide/04_Tool_Calling101.ipynb)

> I am going to develop my own plugin on the server, similar to those that exist today for PhotogenTool, BingSearch, and BraveSearch. It would be more helpful if you could guide me on the path I should take to add this new plugin and inform me if your team plans to improve the integration of a custom function directly on the Llama Stack server so that this custom function becomes part of the execution plan for turn steps.

To add the builtin tool on the server, you can take a look at this [code pointer](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/inline/agents/meta_reference/tools/builtin.py#L2) where existing builtin tools are implemented. We are also in the process of refactoring and improving the registration of tools in Agents, and will keep you updated on our progress!

Hopefully that answers your question a bit. Happy to chat with you in more detail!

**Comment by JoseGuilherme1904** [comment]
Wow, thank you so much [yanxi0830](https://github.com/yanxi0830). I’ll read and study everything very carefully and attentively.

Thank you, thank you so much.
