### ISSUE TITLE
Documentation for adding new Inference Adapter is broken

### ISSUE THREAD

**Issue by sanjayk-github-dev** [meta-llama/llama-stack#431]
### System Info

NA

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

The link for [Inference Remote Adapter](https://github.com/meta-llama/llama-stack/tree/docs/llama_stack/providers/remote/inference)  in the [Developer Guide: Adding a New API Provider](https://github.com/meta-llama/llama-stack/blob/main/docs/source/api_providers/new_api_provider.md#developer-guide-adding-a-new-api-provider) is broken.

### Error logs

NA

### Expected behavior

NA

**Comment by yanxi0830** [comment]
fixed in https://github.com/meta-llama/llama-stack/commit/59a65e34d3cdacd79ff285cd3973712a410401da
