### ISSUE TITLE
Add ability for local persistence for memory adapters

### ISSUE THREAD

**Issue by yanxi0830** [meta-llama/llama-stack#455]
### 🚀 The feature, motivation and pitch

- We want to add ability for persisting local cache for memory adapters

- Code Pointer: 
  - Where pgvector adapter's local cache is defined: https://github.com/meta-llama/llama-stack/blob/4253cfcd7f59fedd4747f706db0fff5971e7c48d/llama_stack/providers/remote/memory/pgvector/pgvector.py#L159-L179
  - chromadb: https://github.com/meta-llama/llama-stack/blob/4253cfcd7f59fedd4747f706db0fff5971e7c48d/llama_stack/providers/remote/memory/chroma/chroma.py#L99-L114
  - weaviate: https://github.com/meta-llama/llama-stack/blob/4253cfcd7f59fedd4747f706db0fff5971e7c48d/llama_stack/providers/remote/memory/weaviate/weaviate.py#L115-L142

- Similar example for inline::faiss memory provider: https://github.com/meta-llama/llama-stack/pull/375

**Comment by hickeyma** [comment]
@yanxi0830 I would like to work on this issue if that's ok?

**Comment by hickeyma** [comment]
Not a bother @dineshyv. That seems a lot simpler alright.

Should this  be implemented in `weaviate` as well?

**Comment by dineshyv** [comment]
I think weaviate already has fallback in case of cache miss: https://github.com/meta-llama/llama-stack/blob/4253cfcd7f59fedd4747f706db0fff5971e7c48d/llama_stack/providers/remote/memory/weaviate/weaviate.py#L151

**Comment by hickeyma** [comment]
Thanks @dineshyv.

@yanxi0830 I think this Issue can be closed as implemented.
