### ISSUE TITLE
Colab links in Zero-Hero would work?

### ISSUE THREAD

**Issue by HamidShojanazeri** [meta-llama/llama-stack#475]
### System Info

I wonder if the colab links in zero-hero notebooks work given that we need to spawn a server that is being accessible on localhost? cc: @heyjustinai 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Run the collab notebook on zero-hero.

### Error logs

N/A

### Expected behavior

being able to hook up local host to colab notebook

**Comment by heyjustinai** [comment]
@HamidShojanazeri, thanks for bringing this up, solving it in PR #447

**Comment by heyjustinai** [comment]
fixed in #447
