### ISSUE TITLE
distro launch documentation error/addition

### ISSUE THREAD

**Issue by DGerhart** [meta-llama/llama-stack#586]
### System Info

r760 xa with 4x L40S

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

if i follow the instructions at this link:  https://llama-stack.readthedocs.io/en/latest/distributions/self_hosted_distro/meta-reference-gpu.html it fails for me every time.  I have to add the following to docker run command for meta reference distro:  i) map host model location to container and ii) allow it to use gpus

### Error logs

this throws errors where it isn't able to find the model in the container  •	Linked here:  [Meta Reference Distribution — llama-stack documentation](https://llama-stack.readthedocs.io/en/latest/distributions/self_hosted_distro/meta-reference-gpu.html)
•	And inline here:  
o	LLAMA_STACK_PORT=5001
o	docker run \
o	  -it \
o	  -p $LLAMA_STACK_PORT:$LLAMA_STACK_PORT \
o	  llamastack/distribution-meta-reference-gpu \
o	  --port $LLAMA_STACK_PORT \
o	  --env INFERENCE_MODEL=meta-llama/Llama-3.2-3B-Instruct
Simply never worked for me ☹

### Expected behavior

The additions of gpu and mapping host to container model location (i.e. –gpus and -v)
•	docker run \
•	--gpus=all \
•	-it \
•	-v ~/.llama:/root/.llama \
•	-p $LLAMA_STACK_PORT:$LLAMA_STACK_PORT \
•	llamastack/distribution-meta-reference-gpu \
•	--port $LLAMA_STACK_PORT \
•	--env INFERENCE_MODEL=Llama3.1-8B-Instruct

**Comment by yanxi0830** [comment]
Thanks! This have been fixed in https://github.com/meta-llama/llama-stack/commit/e2054d53e4aa6b1a8949bd7107e2099aeaf07978
