### ISSUE TITLE
setuptools is now a requirement due to the inclusion of pkg_resources

### ISSUE THREAD

**Issue by kristopolous** [meta-llama/llama-stack#63]
this commit https://github.com/meta-llama/llama-stack/commit/7bc7785b0d0926214c14937ac5598a26e1a62897 right around here: https://github.com/meta-llama/llama-stack/commit/7bc7785b0d0926214c14937ac5598a26e1a62897#diff-d5848a9aa08a98a2cd31b6b2e601f202dd43f5f9d2c95a8037f71e5c4718f0a5R11 introduced a requirement of pkg_resources which can be found in setuptools, which now should be included as a dependency.

Otherwise you get this nasty error when doing step 4 of the official llama-download instructions over here: https://github.com/meta-llama/llama-models/blob/main/README.md
![nasty-error](https://github.com/user-attachments/assets/868afe32-6d02-4279-94cb-8ab9441e61f2)

**Comment by andretf** [comment]
Are you in an isolated env?

```shell
python -m venv llama-env
source llama-env/bin/activate
pip install setuptools
pip install llama-toolchain
llama model list
```

**Comment by kristopolous** [comment]
yes, these are easily fixable things. The package should have it as a requirement and I shouldn't have to manually do it.

I'm not stumped on how to fix it and I don't use the github bug trackers as a troubleshooting forum.

**Comment by ashwinb** [comment]
Ohhh sorry about this, thank you for notifying us about it. Will fix it.

**Comment by ashwinb** [comment]
https://github.com/meta-llama/llama-stack/commit/3e27131a697d47548fd7b6379fc6eed9b99b3cec
