### ISSUE TITLE
Can,t Install LLama cli

### ISSUE THREAD

**Issue by greatermonk** [meta-llama/llama-stack#71]
I have installed llama-toolchain
![Screenshot (5)](https://github.com/user-attachments/assets/98fc405f-68d3-4cec-b9ad-1d0b320b1111)
 but still I am unavailable to run llama commands.

**Comment by ashwinb** [comment]
It appears like you haven't "installed" it, but `git clone`d the repository. That will not make the command available. You need to `pip install llama-stack` (note we have updated the package name now from llama-toolchain to llama-stack.) If you do `git clone`, then you need to do:

```
pip install -e .
```
